version: '1.0'

services:
  nec-sys-api:
    container_name: nec-sys-api
    build:
      context: .
      dockerfile: backend/NecSys.Api/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8085:80

networks:
  default:
      name: srvnecmettin