name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./backend/NecSys.Api
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./backend/NecSys.Api
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./backend/NecSys.Api
    - name: Publish
      run: |
        dotnet publish -c Release -o necsysapi
      working-directory: ./backend/NecSys.Api
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: necsys # Replace with your app name
        publish-profile: $ # Define secret variable in repository settings as per action documentation
        package: './necsysapi' 
